Full definition of S3 client settings.
With default doc options Elasticsearch does not start. For example editing "endpoint" parameter Elasticsearch gives this error:

```
[2020-04-18T11:45:54,211][ERROR][o.e.b.Bootstrap          ] [es-master01] Exception
java.lang.IllegalArgumentException: unknown setting [endpoint] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:532) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:477) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:448) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:419) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:149) ~[elasticsearch-7.6.1.jar:7.6.1]
[...]
```

Reading official documentation says it must be in the following format:

```
s3.client.default.endpoint: my-storage.com
```

https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3-client.html#repository-s3-client